### PR TITLE
Suggestions for everything else

### PR DESCRIPTION
**Pull request by ad71**
In accord with previous suggestions and PRs
`not` should definitely be `cap`
`is` should be `lowkey`
`list` should be `bangers` and you can only have unique bangers in an `album`

and other suggestions I think go with the lingo

### CODE REVIEW

**Comment by shamith09** [comment]
I'm not sure that "cap", "lowkey", "bangers", or "album" qualify as brainrot, since these terms have been in common use for at least the past five years, especially "album" has been around for ages.

**Comment by branyip** [comment]
@shamith09 Pinging you here since I can't make branches without permissions (and therefore can't create a PR). There's a bug in the parser in cases where pygyat tokens that are inside of strings are incorrectly handled (ex. `us-east-1` -> `usdont_use_-_use_fanum taxeastdont_use_-_use_fanum tax1`). 

I have a fix in a local branch I can push up if you want to grant me permissions 🤟

**Comment by ad71** [comment]
@shamith09 Hahah fair!

**Comment by ad71** [comment]
> @shamith09 Pinging you here since I can't make branches without permissions (and therefore can't create a PR). There's a bug in the parser in cases where pygyat tokens that are inside of strings are incorrectly handled (ex. `us-east-1` -> `usdont_use_-_use_fanum taxeastdont_use_-_use_fanum tax1`).
> 
> I have a fix in a local branch I can push up if you want to grant me permissions 🤟

@branyip Fork this repo, push your changes in that and create a PR to this from there, it'll work just fine

**Comment by shamith09** [comment]
+1, @branyip thanks for the flag, I would love to take a look at your fix!

**Pull request closed without merging**
